version: '3'

services:
  php:
    build: php-fpm
    hostname: php
    container_name: php
    volumes:
      - /C/symfonyTest/app/:/var/www/symfony:rw
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - /C/symfonyTest/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /C/symfonyTest/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro